apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-es
  namespace: ${CICD_GIT_REPO_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-es
  template:
    metadata:
      labels:
        app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-es
    spec:
      imagePullSecrets:
      - name: harbor-local    
      containers:
      - name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-es
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        - containerPort: 9300 #Java API port
        env:
        - name: node.name
          value: "Master"
        - name: bootstrap.memory_lock
          value: "true"
        - name: http.cors.allow-origin
          value: "*"
        - name: http.cors.enabled
          value: "true"
        - name: path.data
          value: "/es_data"
        - name: indices.recovery.max_bytes_per_sec
          value: "0"
        - name: refresh_interval
          value: "30s"
        - name: cluster.initial_master_nodes
          value: "Master"
