apiVersion: v1
kind: Service
metadata:
  name: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db-svc
  namespace: ${CICD_GIT_REPO_NAME}
  labels: 
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-db-svc
  annotations:
    iiidevops.org/project_name: ${CICD_GIT_REPO_NAME}
    iiidevops.org/branch: ${CICD_GIT_BRANCH}
    iiidevops.org/commit_id: ${CICD_GIT_COMMIT}
    iiidevops.org/type: web-server
spec:
  type: NodePort
  selector:
    app: ${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}-es
  ports:
    - name: es-tcp-9200
      protocol: TCP
      port: 9200
    - name: es-tcp-9300
      protocol: TCP
      port: 9300
